const cardNames = [
	'0 The Fool.png',
	'1 The Magician.png',
	'2 The High Priestess.png',
	'3 The Empress.png',
	'4 The Emperor.png',
	'5 The Hierophant.png',
	'6 The Lovers.png',
	'7 Chariot.png',
	'8 Justice.png',
	'9 Hermit.png',
	'10 Wheel of Fortune.png',
	'11 Strength.png',
	'12 The Hanged Man.png',
	'13 Death.png',
	'14 Temperance.png',
	'15 The Devil.png',
	'16 The Tower.png',
	'17 The Star.png',
	'18 The Moon.png',
	'19 The Sun.png',
	'20 Judgement.png',
	'21 The World.png',
]

export const tarotCards = [
	// ...cardNames.map((card, idx) => {
	// 	return {
	// 		y: 0,
	// 		x: 0 + 20 * idx + 512 * (idx + 1),
	// 		width: 512,
	// 		height: 768,
	// 		_id: card,
	// 		_type: 'tarotCard',
	// 		cardFilename: card,
	// 		side: 'back',
	// 	}
	// }),
	{
		_type: 'fullDeck',
		y: -1000,
		x: 0,
		width: 512,
		height: 768,
		_id: 'nagleArcanaFull',
		cardImages: cardNames,
		curCard: 0,
	},
	{
		_type: 'tarotDeck',
		y: 100,
		x: 100,
		width: 512,
		height: 768,
		_id: 'nagleArcana',
		cardImages: cardNames,
		addedCards: [],
		curCard: 0,
	},
]
